## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [14]:
import numpy as np
import pandas as pd
import scipy.stats as st


 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
samples =  np.random.normal(loc=100, scale=15, size=1000)
samples

array([135.59151633, 128.03517012,  87.28527474, 111.18557495,
       102.49097763,  91.61364429, 123.80834326, 107.9514333 ,
       127.43743049,  97.3568666 ,  80.91033421,  99.6627923 ,
       114.47375868, 109.52501094, 109.09150702, 107.46204344,
        87.74381237, 102.42501571,  86.83796549,  94.61867743,
        76.78060153,  91.54942726, 101.31208715,  87.45084302,
        93.31251037,  95.93544627,  96.30616365,  86.72860283,
       112.90360766,  96.49087817, 100.750304  , 102.84039365,
       113.5244431 , 106.1298112 ,  91.24137182, 120.10858538,
       106.27009762,  91.15690957, 106.22158111,  75.18139216,
       107.06921042,  89.92843614,  97.00909138, 109.17624924,
       122.91361734, 110.9237311 ,  97.20099109, 114.89808344,
       104.77022993, 105.45381852,  64.32335746,  96.38329452,
        99.85945887, 110.58706131, 112.13121009, 103.03554143,
       100.20370279, 100.27281818, 106.3947723 , 103.02900284,
       109.66384643, 111.12528234,  96.90497168,  95.45

Compute the **mean**, **median**, and **mode**

In [4]:
mean = np.mean(samples)
median = np.median(samples)
mode = st.mode(samples)

print(mean)
print(median)
print(mode)

100.73299853913637
101.496256256545
ModeResult(mode=array([51.42568717]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [5]:
df = pd.DataFrame(samples)

In [6]:
min = df.min()
max = df.max()
q1 = df.quantile(0.25)
q3 = df.quantile(0.75)
iqr = q3 - q1

print(min)
print(max)
print(q1)
print(q3)
print(iqr)

0    51.425687
dtype: float64
0    154.808053
dtype: float64
0    90.526141
Name: 0.25, dtype: float64
0    110.555704
Name: 0.75, dtype: float64
0    20.029563
dtype: float64


Compute the **variance** and **standard deviation**

In [36]:
import statistics as sta

In [8]:
variance = df.var()
std_dev = df.std()

print(variance)
print(std_dev)

0    213.621857
dtype: float64
0    14.615808
dtype: float64


Compute the **skewness** and **kurtosis**

In [9]:
skewness = st.skew(samples)
kurtosis = st.kurtosis(samples)

print(skewness)
print(kurtosis)

-0.09302954151815611
0.12285515707141403


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [10]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [11]:
y = np.array(np.random.rand(10))
y

array([0.64113046, 0.53149905, 0.84919146, 0.92591114, 0.29442452,
       0.72606888, 0.90526611, 0.93403299, 0.10064074, 0.62856521])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [30]:
r =  np.corrcoef(x,y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [33]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [41]:
df3 = pd.DataFrame([x, y]).T
df3

0   1
0  10   2
1  11   1
2  12   4
3  13   5
4  14   8
5  15  12
6  16  18
7  17  25
8  18  96
9  19  48

In [42]:
df3.corr()

0        1
0  1.00000  0.75864
1  0.75864  1.00000

In [37]:
r = st.pearsonr(x,y)
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [43]:
rho = df3.corr(method="spearman")
rho

0         1
0  1.000000  0.975758
1  0.975758  1.000000

## Seaborn Dataset Tips

Import Seaborn Library

In [44]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [46]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [47]:
tips.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [48]:
tips.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000