In [3]:
import pandas as pd

In [3]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
seri = pd.Series([1088,3,4,5])

In [5]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [6]:
seri.size

4

In [7]:
seri.values

array([1088,    3,    4,    5], dtype=int64)

In [8]:
seri.head(3)  # ilk üç indexi getirir

0    1088
1       3
2       4
dtype: int64

In [9]:
seri.tail(3)#son üç indexi getirir

1    3
2    4
3    5
dtype: int64

#index isimlendirmesi

In [10]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [11]:
pd.Series([99,22,332,94,5], index = [1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [13]:
pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [18]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

In [19]:
seri["a"]

99

In [20]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [ ]:
# sözlük üzerinden liste oluşturma

In [22]:
sozluk = {"reg":10, "log":11, "cart":2}
seri = pd.Series(sozluk)
seri

reg     10
log     11
cart     2
dtype: int64

In [23]:
seri["reg"]

10

In [ ]:
# iki seriyi birleştirerek seri oluşturma

In [27]:
sozluk = {"reg":10, "log":11, "cart":2}
seri = pd.Series(sozluk)

seri2 = pd.Series({"adı": "jack", "soyadı":"sellow", "yaş":47})

pd.concat([seri,seri2])

reg           10
log           11
cart           2
adı         jack
soyadı    sellow
yaş           47
dtype: object

In [ ]:
# ELEMAN İŞLEMLERİ

In [4]:
import numpy as np

In [30]:
a = np.arange(100,110 )
seri = pd.Series(a)
seri

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int32

In [31]:
seri[0:3]

0    100
1    101
2    102
dtype: int32

In [32]:
seri = pd.Series([121,200,150,99], index = ["reg", "loj", "cart", "rf"] )
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [33]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [34]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [35]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [ ]:
# Eleman sorgulama

In [36]:
"reg" in seri

True

In [ ]:
# fancy eleman

In [37]:
seri[["rf", "reg"]]

rf      99
reg    121
dtype: int64

In [38]:
seri["reg"] = 1706
seri

reg     1706
loj      200
cart     150
rf        99
dtype: int64

In [39]:
seri = pd.Series([121,200,150,99], index = ["reg", "loj", "cart", "rf"] )

In [40]:
seri["reg":"cart"]

reg     121
loj     200
cart    150
dtype: int64

In [ ]:
# Pandas DataFrame oluşturma

In [42]:
myList = [1,2,39,67,90]
pd.DataFrame(myList)


0
0   1
1   2
2  39
3  67
4  90

In [43]:
pd.DataFrame(myList, columns=["değişken ismi"])


değişken ismi
0              1
1              2
2             39
3             67
4             90

In [8]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
df = pd.DataFrame(m, columns=["var1", "var2", "var3"])
df


var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [10]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
# df isimlendirme

In [12]:
df.columns = ("new1", "new2", "new3")
df

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [13]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['new1', 'new2', 'new3'], dtype='object')]

In [14]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
df.head(2)

new1  new2  new3
0     1     2     3
1     4     5     6

In [20]:
df.tail(1)

new1  new2  new3
2     7     8     9

In [21]:
a = np.array([1,2,3,4,5])

In [22]:
pd.DataFrame(a, columns = ["sat"])

sat
0    1
1    2
2    3
3    4
4    5